#!/usr/bin/env python3
"""
Generate init_clickhouse.sql from the schema defined in app.py's init_db() function.

This script extracts the CREATE TABLE statements from app.py and generates
a corresponding SQL file for reference and manual initialization purposes.
The app.py file remains the single source of truth for the schema.

Usage:
    python generate_schema_sql.py
    # or
    make generate-schema-sql
"""

import re
import os
from datetime import datetime


def extract_schema_from_app():
    """Extract CREATE TABLE statements from app.py's init_db() function."""
    
    # Read app.py
    script_dir = os.path.dirname(os.path.abspath(__file__))
    app_py_path = os.path.join(script_dir, 'app.py')
    
    with open(app_py_path, 'r') as f:
        content = f.read()
    
    # Find the init_db function
    init_db_match = re.search(r'def init_db\(\):.*?(?=\ndef\s|\nif\s__name__|$)', content, re.DOTALL)
    if not init_db_match:
        raise ValueError("Could not find init_db() function in app.py")
    
    init_db_content = init_db_match.group(0)
    
    # Extract CREATE TABLE statements (looking for triple-quoted strings)
    create_statements = re.findall(r"client\.command\(f?'''(.*?)'''", init_db_content, re.DOTALL)
    
    if not create_statements:
        raise ValueError("Could not find CREATE TABLE statements in init_db()")
    
    # Get the database name from DB_CONFIG
    db_name_match = re.search(r"'database':\s*os\.environ\.get\('DB_NAME',\s*'([^']+)'\)", content)
    database_name = db_name_match.group(1) if db_name_match else 'baby_tracker'
    
    return database_name, create_statements


def process_create_statement(statement):
    """
    Process a CREATE TABLE statement to replace timezone references.
    
    Replaces {LOCAL_TIMEZONE.zone} with 'Asia/Kolkata' and adds a note
    about timezone configuration.
    """
    # Replace f-string timezone interpolation with a static timezone
    # Note: The pattern needs to account for the quotes already in the source
    processed = re.sub(r"\{LOCAL_TIMEZONE\.zone\}", "Asia/Kolkata", statement)
    
    # Remove leading/trailing whitespace from the entire block
    processed = processed.strip()
    
    # Find the minimum indentation (excluding empty lines)
    lines = processed.split('\n')
    non_empty_lines = [line for line in lines if line.strip()]
    if non_empty_lines:
        min_indent = min(len(line) - len(line.lstrip()) for line in non_empty_lines)
        # Remove the minimum indentation from all lines
        processed = '\n'.join(
            line[min_indent:] if len(line) > min_indent else line
            for line in lines
        )
    
    # Clean up any trailing whitespace on each line
    processed = '\n'.join(line.rstrip() for line in processed.split('\n'))
    
    # Indent the table definition properly (4 spaces after CREATE TABLE line)
    lines = processed.split('\n')
    result_lines = []
    in_column_definition = False
    
    for i, line in enumerate(lines):
        stripped = line.strip()
        if i == 0:  # First line (CREATE TABLE)
            result_lines.append(line)
            in_column_definition = True
        elif stripped.startswith(')'):  # End of column definition
            result_lines.append('    ' + line.lstrip())
            in_column_definition = False
        elif in_column_definition and stripped and not stripped.startswith('CREATE'):
            # Column definitions - indent with 4 spaces
            result_lines.append('    ' + line.lstrip())
        elif stripped.startswith(('ORDER BY', 'PRIMARY KEY', 'PARTITION BY', 'TTL', 'SETTINGS', 'ENGINE')):
            # Table properties - no extra indent
            result_lines.append(line.lstrip())
        else:
            result_lines.append(line)
    
    return '\n'.join(result_lines)



def generate_sql_file(database_name, create_statements):
    """Generate the init_clickhouse.sql file with proper documentation."""
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    header = f"""-- Initialize the baby tracker database in ClickHouse
-- 
-- AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
-- Generated on: {timestamp}
-- Source: app.py init_db() function
-- Generator: generate_schema_sql.py
-- 
-- This file is automatically generated from the schema defined in app.py's init_db()
-- function, which is the single source of truth for the database schema at runtime.
-- 
-- To regenerate this file after modifying app.py:
--   python generate_schema_sql.py
--   OR
--   make generate-schema-sql
-- 
-- PURPOSE:
-- This file is provided for:
-- 1. Reference documentation of the schema structure
-- 2. Manual database initialization if needed (e.g., for testing or external tools)
-- 3. Schema review and version control purposes
-- 
-- IMPORTANT NOTES:
-- - The application (app.py) automatically creates these tables with the correct
--   schema including timezone-aware DateTime64 types on startup.
-- - The timezone shown here ('Asia/Kolkata') is the default; app.py uses the
--   TZ environment variable or LOCAL_TIMEZONE configuration at runtime.
-- - If you modify the schema, update app.py's init_db() function and regenerate
--   this file to maintain consistency.

-- Create database
CREATE DATABASE IF NOT EXISTS {database_name};

-- Use the database
USE {database_name};

"""
    
    # Process each CREATE TABLE statement
    table_sqls = []
    for i, statement in enumerate(create_statements):
        processed = process_create_statement(statement)
        
        # Add notes for specific tables
        if 'entries_backup' in processed:
            note = ("-- Create backup table for update rollback support\n"
                    "-- This matches the entries table structure for proper data type compatibility\n"
                    "-- Note: If used manually, replace 'Asia/Kolkata' with your timezone (app.py uses LOCAL_TIMEZONE)\n"
                    "-- Note: backup_id must be explicitly provided by the application (generated as UUID)\n")
        elif 'entries' in processed and 'entries_backup' not in processed:
            note = ("-- Create entries table using MergeTree engine for optimal performance\n"
                    "-- Note: If used manually, replace 'Asia/Kolkata' with your timezone (app.py uses LOCAL_TIMEZONE)\n")
        else:
            note = ""
        
        table_sqls.append(note + processed + ';')
    
    footer = """
-- Note: IDs are not auto-incremented in ClickHouse; the application layer must provide unique IDs
"""
    
    return header + '\n'.join(table_sqls) + footer


def main():
    """Main function to generate the SQL file."""
    try:
        print("Extracting schema from app.py...")
        database_name, create_statements = extract_schema_from_app()
        
        print(f"Found {len(create_statements)} CREATE TABLE statement(s)")
        print("Generating init_clickhouse.sql...")
        
        sql_content = generate_sql_file(database_name, create_statements)
        
        # Write to file
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_path = os.path.join(script_dir, 'init_clickhouse.sql')
        
        with open(output_path, 'w') as f:
            f.write(sql_content)
        
        print(f"Successfully generated {output_path}")
        print("\nThe init_clickhouse.sql file has been regenerated from app.py.")
        print("Review the changes to ensure the schema is correct.")
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)


if __name__ == '__main__':
    main()
