-- Initialize the baby tracker database in ClickHouse
-- 
-- AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
-- Generated on: 2026-01-02 19:04:13 UTC
-- Source: app.py init_db() function
-- Generator: generate_schema_sql.py
-- 
-- This file is automatically generated from the schema defined in app.py's init_db()
-- function, which is the single source of truth for the database schema at runtime.
-- 
-- To regenerate this file after modifying app.py:
--   python generate_schema_sql.py
--   OR
--   make generate-schema-sql
-- 
-- PURPOSE:
-- This file is provided for:
-- 1. Reference documentation of the schema structure
-- 2. Manual database initialization if needed (e.g., for testing or external tools)
-- 3. Schema review and version control purposes
-- 
-- IMPORTANT NOTES:
-- - The application (app.py) automatically creates these tables with the correct
--   schema including timezone-aware DateTime64 types on startup.
-- - The timezone shown here ('Asia/Kolkata') is the default; app.py uses the
--   TZ environment variable or LOCAL_TIMEZONE configuration at runtime.
-- - If you modify the schema, update app.py's init_db() function and regenerate
--   this file to maintain consistency.

-- Create database
CREATE DATABASE IF NOT EXISTS baby_tracker;

-- Use the database
USE baby_tracker;

-- Create entries table using MergeTree engine for optimal performance
-- Note: If used manually, replace 'Asia/Kolkata' with your timezone (app.py uses LOCAL_TIMEZONE)
CREATE TABLE IF NOT EXISTS entries (
    id UInt32,
    temperature Nullable(Decimal32(1)),
    feed_amount Nullable(UInt16),
    feed_type Nullable(String),
    susu_count UInt16 DEFAULT 0,
    poti_count UInt16 DEFAULT 0,
    poti_color Nullable(String),
    weight Nullable(UInt16),
    notes Nullable(String),
    timestamp DateTime64(3, 'Asia/Kolkata'),
    created_at DateTime64(3, 'Asia/Kolkata')
    ) ENGINE = MergeTree()
ORDER BY (timestamp, id)
PRIMARY KEY (timestamp, id)
PARTITION BY toYYYYMM(timestamp)
SETTINGS index_granularity = 8192;
-- Create backup table for update rollback support
-- This matches the entries table structure for proper data type compatibility
-- Note: If used manually, replace 'Asia/Kolkata' with your timezone (app.py uses LOCAL_TIMEZONE)
-- Note: backup_id must be explicitly provided by the application (generated as UUID)
CREATE TABLE IF NOT EXISTS entries_backup (
    id UInt32,
    temperature Nullable(Decimal32(1)),
    feed_amount Nullable(UInt16),
    feed_type Nullable(String),
    susu_count UInt16 DEFAULT 0,
    poti_count UInt16 DEFAULT 0,
    poti_color Nullable(String),
    weight Nullable(UInt16),
    notes Nullable(String),
    timestamp DateTime64(3, 'Asia/Kolkata') DEFAULT now64(3, 'Asia/Kolkata'),
    created_at DateTime64(3, 'Asia/Kolkata') DEFAULT now64(3, 'Asia/Kolkata'),
    backup_timestamp DateTime64(3, 'Asia/Kolkata') DEFAULT now64(3, 'Asia/Kolkata'),
    backup_id String NOT NULL
    ) ENGINE = MergeTree()
ORDER BY (id, backup_timestamp, backup_id)
PRIMARY KEY (id, backup_timestamp, backup_id)
TTL backup_timestamp + INTERVAL 1 DAY
SETTINGS index_granularity = 8192;
-- Note: IDs are not auto-incremented in ClickHouse; the application layer must provide unique IDs
